version: '3'

services:
  db: 
    build: ./db
    environment:
      MYSQL_DATABASE: bookdatabase
      MYSQL_ROOT_PASSWORD: thddnjs12!
      MYSQL_USER: root
      MYSQL_PASSWORD: thddnjs12!
      DATABASE_HOST: db
    restart: always
    volumes:
      - mysqldata
  
  web:
    build: ./web
    environment:
      MYSQL_DATABASE: bookdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: thddnjs12!
      MYSQL_PORT: 3306
      DATABASE_HOST: db
    ports: 
      # - 는 배열이라는 뜻이다.
      - "8080:8080"
    depends_on: 
      - db
    # node js가 더 빨리 빌드될 가능성이 있기에 failure가 될 경우 그냥 다시 하도록 한다.
    restart: on-failure


  